"""create test tables

Revision ID: 296a1bc9e8bb
Revises: bed98ffd4497
Create Date: 2024-07-22 15:36:35.688307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "296a1bc9e8bb"
down_revision: Union[str, None] = "bed98ffd4497"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
