"""create test tables

Revision ID: dffad2ea7e30
Revises: 7f7a7aa901ee
Create Date: 2024-07-22 16:56:00.102945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dffad2ea7e30"
down_revision: Union[str, None] = "7f7a7aa901ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
