"""create test tables

Revision ID: 947ffe03bd3e
Revises: d43dfb6f111e
Create Date: 2024-07-22 15:56:14.111110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "947ffe03bd3e"
down_revision: Union[str, None] = "d43dfb6f111e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
