"""create test tables

Revision ID: a9dff0cfd5fe
Revises: 1e8cc46b6563
Create Date: 2024-07-22 17:10:40.096554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9dff0cfd5fe"
down_revision: Union[str, None] = "1e8cc46b6563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
